# Generated by Django 6.0.5 on 2026-05-30 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_name', models.CharField(default='dee-lou', max_length=100)),
                ('avatar_path', models.CharField(default='test-images/dLU-right.png', max_length=220)),
                ('realtime_model', models.CharField(default='gpt-realtime-mini', max_length=100)),
                ('voice', models.CharField(default='ash', max_length=40)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('voice_instructions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tutor settings',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tutoringsession',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.experience'),
        ),
        migrations.AddIndex(
            model_name='tutoringsession',
            index=models.Index(fields=['experience', '-updated_at'], name='core_tutori_experie_39db3f_idx'),
        ),
        migrations.AddField(
            model_name='tutorsettings',
            name='experience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_settings', to='core.experience'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['user', '-updated_at'], name='core_experi_user_id_21dcdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_user_experience_slug'),
        ),
    ]
