# Generated by Django 6.0.5 on 2026-05-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_eventactionstep_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventactionstep',
            name='action_type',
            field=models.CharField(choices=[('script', 'Script'), ('set_context', 'Set context'), ('get_ui_state', 'Get UI state'), ('highlight_on', 'Highlight on'), ('highlight_off', 'Highlight off'), ('set_ui_trigger', 'Set UI trigger'), ('goto_event', 'Go to event'), ('button_choice', 'Button choice')], default='script', max_length=40),
        ),
    ]
