# Generated by Codex on 2026-05-30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_eventactionstep_action_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventChatTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "triggers_event",
                    models.SlugField(blank=True, default="", max_length=180),
                ),
                (
                    "save_argument",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "save_context_key",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_tools",
                        to="core.experienceevent",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="eventchattool",
            index=models.Index(
                fields=["event", "sort_order"],
                name="core_eventc_event_i_4c7224_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventchattool",
            constraint=models.UniqueConstraint(
                fields=("event", "name"),
                name="unique_event_chat_tool_name",
            ),
        ),
    ]
