# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_eventchattool"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventchattool",
            name="handler_actions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
