# Generated by Codex on 2026-05-30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_eventchattool_handler_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventConversationCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="Check", max_length=160)),
                ("instructions", models.TextField(blank=True, default="")),
                (
                    "result_context_key",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("handler_actions", models.JSONField(blank=True, default=list)),
                (
                    "triggers_event",
                    models.SlugField(blank=True, default="", max_length=180),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_checks",
                        to="core.experienceevent",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="eventconversationcheck",
            index=models.Index(
                fields=["event", "sort_order"],
                name="core_eventc_check_e_0cdcc0_idx",
            ),
        ),
    ]
