# Generated by Codex on 2026-05-30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_eventconversationcheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="experienceevent",
            name="chat_instructions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="eventactionstep",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("script", "Script"),
                    ("set_context", "Set context"),
                    ("append_context_list", "Append context list"),
                    ("get_ui_state", "Get UI state"),
                    ("highlight_on", "Highlight on"),
                    ("highlight_off", "Highlight off"),
                    ("set_ui_trigger", "Set UI trigger"),
                    ("goto_event", "Go to event"),
                    ("button_choice", "Button choice"),
                ],
                default="script",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="EventClassifierGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="Classifier group",
                        max_length=160,
                    ),
                ),
                ("instructions", models.TextField(blank=True, default="")),
                (
                    "result_context_key",
                    models.CharField(
                        blank=True,
                        default="_classifier_results",
                        max_length=120,
                    ),
                ),
                ("handler_actions", models.JSONField(blank=True, default=list)),
                (
                    "triggers_event",
                    models.SlugField(blank=True, default="", max_length=180),
                ),
                ("condition", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifier_groups",
                        to="core.experienceevent",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventClassifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("prompt", models.TextField(blank=True, default="")),
                ("schema", models.JSONField(blank=True, default=dict)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("condition", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifiers",
                        to="core.eventclassifiergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="eventclassifiergroup",
            index=models.Index(
                fields=["event", "sort_order"],
                name="core_eventcl_group_73c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventclassifier",
            index=models.Index(
                fields=["group", "sort_order"],
                name="core_eventcl_class_2576_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventclassifier",
            constraint=models.UniqueConstraint(
                fields=("group", "name"),
                name="unique_event_classifier_name",
            ),
        ),
    ]
