# Generated by Django 6.0.6 on 2026-06-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_experience_side_panels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventactionstep',
            name='action_type',
            field=models.CharField(choices=[('script', 'Script'), ('set_context', 'Set context'), ('append_context_list', 'Append context list'), ('get_ui_state', 'Get UI state'), ('highlight_on', 'Highlight on'), ('highlight_off', 'Highlight off'), ('interactive', 'Interactive'), ('interactive_update', 'Update interactive'), ('interactive_clear', 'Clear interactive'), ('python_notebook', 'Python notebook'), ('chat_availability', 'Chat availability'), ('set_ui_trigger', 'Set UI trigger'), ('side_panel', 'Side panel'), ('roadmap_complete', 'Roadmap complete'), ('goto_event', 'Go to event'), ('button_choice', 'Button choice')], default='script', max_length=40),
        ),
    ]
